### PR TITLE
Follow upstream Nixpkgs style guidelines

### PR DESCRIPTION
**Pull request by max-niederman**
Eventually, all of the packages and most of the NixOS modules from this repository should be upstreamed into Nixpkgs.
To that end, we should follow Nixpkgs contribution guidelines whenever possible.

In the future, I'd also like to add nixpkgs-fmt as a CI check.

### CODE REVIEW

**Comment by ArchB1W** [comment]
If we're gonna use `nixpkgs-fmt` it'd make sense to add it to the `flake.nix` (under `formatter`) so then you can just run `nix fmt` and format every file in repo.

**Review by ArchB1W — CHANGES_REQUESTED** [review]
Oops I didn’t realize I could put my comment in as “Request Changes.” Everything here so far looks good to me. If we're gonna use a specific formatter it'd make sense to add it to the `flake.nix` (under `formatter`) so then you can just run `nix fmt` and format every file in repo.

**Comment by max-niederman** [comment]
> Oops I didn’t realize I could put my comment in as “Request Changes.” Everything here so far looks good to me. If we're gonna use a specific formatter it'd make sense to add it to the `flake.nix` (under `formatter`) so then you can just run `nix fmt` and format every file in repo. After that I’d also have a separate commit where you actually run the formatter and keep `git blame` working add it `.git-blame-ignore-revs` then add that to the the local git config with `git config blame.ignoreRevsFile .git-blame-ignore-revs`

Just added nixpkgs-fmt to the flake outputs. Thanks for the suggestion, I wasn't aware `nix fmt` even existed tbh.

**Review by ArchB1W — APPROVED** [review]
LGTM. I'll let you merge it once you want.

**Pull request merged**
